version: '3.8'
services:
  funasr_service:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              ## 显式指定显卡
              device_ids: ["2", "3"]
              #count: "all"
              capabilities: [gpu]
    volumes:
      - ./models/SenseVoiceSmall:/app/models/SenseVoiceSmall
      - ./models/ct-punc:/app/models/ct-punc
    ports:
      - "8000:8000"
    environment:
      ## 语音识别模型
      - AUDIO_MODEL_DIR=/app/models/SenseVoiceSmall
      ## 标点恢复模型
      - CT_PUNC_MODEL_DIR=/app/models/ct-punc
    working_dir: /app

networks:
  default:
    driver: bridge
